import ctypes
import os

from .err import EDS_ERR_OK, ERROR_CODE_NAMES, CameraException
from .properties import EdsPropertyIDEnum, _property_callback
from .sdk import (
    EdsError,
    EdsBaseRef,
    EdsCameraListRef,
    EdsCameraRef,
    EdsEvfImageRef,
    EdsStreamRef,
    EdsDirectoryItemRef,
    EdsInt32,
    EdsUInt32,
    EdsInt64,
    EdsUInt64,
    EdsPropertyID,
    EdsPropertyEvent,
    kEdsPropertyEvent_PropertyChanged,
    EdsDeviceInfo,
    EdsDirectoryItemInfo,
    EdsPropertyEventHandler,
    EdsObjectEventHandler,
    EdsCameraAddedHandler,
    edsdk,
    kEdsCameraCommand_TakePicture,
    kEdsCameraCommand_PressShutterButton,
    kEdsCameraCommand_ShutterButton_Completely_NonAF,
    kEdsCameraCommand_ShutterButton_OFF,
    kEdsCameraCommand_DoEvfAf,
    kEdsCameraCommand_ShutterButton_Halfway,
    kEdsObjectEvent_All,
    kEdsObjectEvent_DirItemCreated,
    kEdsObjectEvent_DirItemRequestTransfer,
)


__all__ = [
    "EdsPropertyIDEnum",
    "EDS_ERR_OK",
    "ERROR_CODE_NAMES",
    "EdsError",
    "EdsBaseRef",
    "EdsCameraListRef",
    "EdsCameraRef",
    "EdsEvfImageRef",
    "EdsStreamRef",
    "EdsDirectoryItemRef",
    "EdsInt32",
    "EdsUInt32",
    "EdsInt64",
    "EdsUInt64",
    "EdsPropertyID",
    "EdsPropertyEvent",
    "kEdsPropertyEvent_PropertyChanged",
    "EdsDeviceInfo",
    "EdsDirectoryItemInfo",
    "EdsPropertyEventHandler",
    "EdsObjectEventHandler",
    "EdsCameraAddedHandler",
    "edsdk",
    "kEdsCameraCommand_TakePicture",
    "kEdsCameraCommand_PressShutterButton",
    "kEdsCameraCommand_ShutterButton_Completely_NonAF",
    "kEdsCameraCommand_ShutterButton_OFF",
    "kEdsCameraCommand_DoEvfAf",
    "kEdsCameraCommand_ShutterButton_Halfway",
    "kEdsObjectEvent_All",
    "kEdsObjectEvent_DirItemCreated",
    "kEdsObjectEvent_DirItemRequestTransfer",
    "_property_callback",
    "CameraException",
]
